spring:
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: 
            clientSecret: 
          google:
            client-id: 
            client-secret:


telegram:
   bot:
    token: 
    chatId: 
    username: 
vaadin:
  servlet:
    blacklisted-classes: 

