
spring:
  security:
    oauth2:
      client:
        registration:
          github:
            scope=openid:
            clientId: 76aea9fb3a42c886d491
            clientSecret: 847f8b572c054f089fcdaa2d017cf6f62b6ef2c3
          google:
            client-id: 544172631662-3sj598scne4q72lr9ou99b2ubf7ire7r.apps.googleusercontent.com
            client-secret: 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

logging:
  level:
    org.springframework.security: DEBUG